[package]
name = "simple-cms"
version = "0.1.0"
authors = ["Markus Murto <markus@murto.eu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
